name: Build Windows (Latest)

on:
  workflow_dispatch: # Allows you to trigger the workflow manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write build date badge JSON
        if: ${{ success() }}
        run: |
          $date = Get-Date -Format "yyyy-MM-dd HH:mm"
          $json = "{ `"schemaVersion`": 1, `"label`": `"last build`", `"message`": `"$date UTC`", `"color`": `"blue`" }"
          Set-Content -Path build-date-badge.json -Value $json

      - name: Run Zandronum build script
        shell: pwsh
        run: |
          ./build.ps1

      - name: Validate executable runs (no missing DLLs)
        run: |
          Write-Host "Testing executable can run without DLL errors..."
          # Test with -iwad parameter pointing to nonexistent file - should fail gracefully, not with DLL error
          $output = .\build\Release\zandronum.exe -iwad nonexistent.wad 2>&1 | Out-String
          Write-Host "Zandronum output: $output"
          # If it's a DLL error, it will contain "dll" or "library" 
          if ($output -match "(?i)(dll|library|api-ms-|vcruntime|msvcp)" -and $output -notmatch "(?i)(iwad|wad)") {
            Write-Host "❌ DLL dependency error detected"
            exit 1
          } else {
            Write-Host "✅ No DLL errors - executable can start properly"
          }

      - name: Write Zandronum version badge JSON
        if: ${{ success() }}
        run: |
          $tagLine = Get-Content src/zandronum/.hgtags | Where-Object { $_.Trim() -ne "" } | Select-Object -Last 1
          if ($tagLine) {
            $version = $tagLine -split " " | Select-Object -Last 1
          } else {
            $version = "unknown"
          }
          $json = "{ `"schemaVersion`": 1, `"label`": `"zandronum`", `"message`": `"$version`", `"color`": `"orange`" }"
          Set-Content -Path zandronum-version-badge.json -Value $json
      - name: Push badge files to badges branch
        if: ${{ success() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin badges || true
          git checkout -B badges
          git add build-date-badge.json zandronum-version-badge.json
          git commit -m "Update badges" || exit 0
          Write-Host "Setting remote URL with GITHUB_TOKEN..."
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          Write-Host "Pushing to badges branch..."
          git push origin badges --force