name: Build Windows (Windows 10 Mock)

on:
  workflow_dispatch:

jobs:
  windows-10-compat:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check PowerShell Version
        shell: cmd
        run: |
          "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -Command "$PSVersionTable"

      - name: Remove system Python to test portable install
        shell: cmd
        run: |
          "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -Command ^
          "Write-Host 'Removing Python from PATH environment...'; ^
          $currentPath = $env:PATH; ^
          Write-Host 'Current PATH contains Python at:'; ^
          $currentPath -split ';' ^| Where-Object { $_ -like '*Python*' }; ^
          $newPath = ($currentPath -split ';' ^| Where-Object { $_ -notlike '*Python*' -and $_ -notlike '*hostedtoolcache*' }) -join ';'; ^
          $env:PATH = $newPath; ^
          'PATH=' + $newPath ^| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append; ^
          Write-Host 'Python paths removed from environment'"

      - name: Validate Python removal
        shell: cmd
        run: |
          echo Validating that no Python is available in PATH...
          where python >nul 2>&1 && echo ERROR: Python found && exit /b 1
          echo SUCCESS: No Python found in PATH - portable install will be used

      - name: Run Zandronum build script
        shell: cmd
        run: |
          "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -File "build.ps1"
