name: Test Secret Debug

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test all secrets
        run: |
          echo "Testing GH_PAT: '${GH_PAT}'"
          echo "GH_PAT length: ${#GH_PAT}"
          if [ -z "$GH_PAT" ]; then 
            echo "❌ GH_PAT is empty or not set"
          else 
            echo "✅ GH_PAT is set (${#GH_PAT} chars)"
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      
      - name: List available secrets (names only)
        run: |
          echo "Secrets context available:"
          echo "${{ toJson(secrets) }}" | jq -r 'keys[]' || echo "No secrets or jq not available"
